version: '3'
services:
  app:
    restart: always
    container_name: lambda_fastapi_app
    hostname: gt_server
    build: .
    tty: true
    ports:
      - ${APP_PORT:-80}:80
    env_file:
      - app.env
    volumes:
      - ../../api:/api
    working_dir: /api
    # command: bash -c "poetry install && /bin/bash"
    networks:
      - lambda_fastapi_backend

  db:
    image: mysql:8.0
    restart: always
    container_name: lambda_fastapi_db
    hostname: gt_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local_db
      MYSQL_USER: as
      MYSQL_PASSWORD: os
      TZ: Asia/Tokyo
    ports:
      - ${DB_PORT:-3306}:3306
    # データを永続化させる場合
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./mysql/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./mysql/mysql_data:/var/lib/mysql
      # 設定系
      - ./mysql/conf.d:/etc/mysql/conf.d:sensitive
    # command: ['mysqld', '--lower_case_table_names=0']
    networks:
      - lambda_fastapi_backend

networks:
  lambda_fastapi_backend:
    external: true
